### ISSUE TITLE
Please Remove Proguard OR

### ISSUE THREAD

**Issue by Nyfaria** [NeRdTheNed/More-bows#11]
Please Remove Proguard's Obfuscation OR create a non-Obfuscated Maven so I, and probably others, can create Mod Compatibility between our mods.

**Comment by NeRdTheNed** [comment]
Hey @Nyfaria, is there a specific class or method you'd like me to not obfuscate? I upload a version of More Bows without any obfuscation with a "-debug" classifier, but I don't currently have a Maven repository.

**Comment by NeRdTheNed** [comment]
Hey @Nyfaria, does 7de021ddfd5e0e5f4dc480ea4253de14554cbebc fix this?

**Comment by Nyfaria** [comment]
tbh i am not 100% sure how proguard works, i just know i can't write mixins into your obfuscated classes dont work, so as long as they aren't obfuscated in the jar it should be fine.

**Comment by NeRdTheNed** [comment]
Should be fixed in the latest release.
