### ISSUE TITLE
Mod encountered an error during event phase

### ISSUE THREAD

**Issue by GitUser14975** [NeRdTheNed/More-bows#13]
Hi, I got an error saying that more bows enountered an error during event setup phase(?) or something like that

https://gist.github.com/TenKotowsky/eb55763fc3561c89dba37ca444f23c7a

**Comment by NeRdTheNed** [comment]
Found the cause of the bug: ItemProperties.register needs to be handled in a thread safe way on Forge. Working on a fix.

**Comment by NeRdTheNed** [comment]
@TenKotowsky Does this snapshot build fix the issue? https://github.com/NeRdTheNed/More-bows/suites/13970833813/artifacts/778952066

**Comment by NeRdTheNed** [comment]
Likely fixed in v1.0.12.
